"""Typed governance events.

All audit-relevant happenings in the system emit a typed event into the
governance event store. The store is a Delta table; batches of events are
periodically Merkle-rooted and anchored on-chain.

Event types covered:
  - QuarantineEvent: a record was rejected at the Silver layer
  - PromotionEvent: an MLflow model version was promoted between stages
  - InferenceEvent: an alert was generated by the scoring job
  - AnchorEvent: a Merkle root was committed on-chain
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal
from uuid import uuid4

from pydantic import BaseModel, Field

from swift_audit.hashing import sha256_hex


class EventType(str, Enum):
    QUARANTINE = "quarantine"
    PROMOTION = "promotion"
    INFERENCE = "inference"
    ANCHOR = "anchor"


class _BaseEvent(BaseModel):
    """Fields shared by every governance event."""

    event_id: str = Field(default_factory=lambda: str(uuid4()))
    event_type: EventType
    occurred_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    actor: str  # who triggered this (system process or human approver)
    payload: dict[str, Any]

    def to_hash(self) -> str:
        """Canonical hash of the event — the leaf value used in Merkle trees."""
        return sha256_hex(
            {
                "event_id": self.event_id,
                "event_type": self.event_type.value,
                "occurred_at": self.occurred_at,
                "actor": self.actor,
                "payload": self.payload,
            }
        )


class QuarantineEvent(_BaseEvent):
    event_type: Literal[EventType.QUARANTINE] = EventType.QUARANTINE


class PromotionEvent(_BaseEvent):
    """A model promotion between MLflow registry stages.

    Required payload keys:
      - model_name: registered model name
      - model_version: integer version that was promoted
      - from_stage / to_stage: e.g. "Staging" -> "Production"
      - metrics: dict of metric_name -> value at the promotion gate
      - mlflow_run_id: run that produced this version
    """

    event_type: Literal[EventType.PROMOTION] = EventType.PROMOTION


class InferenceEvent(_BaseEvent):
    """A scoring decision emitted by the production model.

    Required payload keys:
      - alert_id: stable identifier for downstream replay
      - input_hash: canonical hash of the feature row (from hashing.sha256_hex)
      - gold_snapshot_version: Delta version of the Gold table at scoring time
      - model_name / model_version: registered model used for the prediction
      - score: anomaly score
      - decision: e.g. "alert" / "clear"
    """

    event_type: Literal[EventType.INFERENCE] = EventType.INFERENCE


class AnchorEvent(_BaseEvent):
    """A Merkle root committed to the external ledger.

    Required payload keys:
      - batch_id: stable batch identifier
      - merkle_root: hex digest of the root
      - leaf_count: number of events in the batch
      - tx_hash: on-chain transaction hash
      - block_number: block height at which the tx was mined
    """

    event_type: Literal[EventType.ANCHOR] = EventType.ANCHOR
