[package]
name = "auditable-ai-lakehouse"
version = "1.0.0"
authors = []

[addresses]
auditable_ai_lakehouse = "_"

[dev-addresses]
auditable_ai_lakehouse = "0xc1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
